// sales-plays.js — the versioned commercial strategy (Business Plan 2026, Part IV §36–37).
// A SalesPlay is the atomic commercial hypothesis. Every prospect must attach to
// exactly one play before contact research or drafting. Strategy is versioned;
// operational code must never mutate a play in place — bump STRATEGY_VERSION and
// add a new revision instead.
export const STRATEGY_VERSION = "plan-2026-07-10";

export const SALES_PLAYS = [
  {
    play_id: "GNK-PROD-01",
    brand: "gnk",
    strategy_version: STRATEGY_VERSION,
    name: "Senior Engineering Delivery Sprint",
    target_account_definition: "Established B2B/vertical software company (≈50–500 employees) with a delayed or difficult product slice that internal teams cannot prioritize cleanly.",
    hard_disqualifiers: ["pre-product startup", "commodity website work", "procurement-only enterprise transformation", "no owner who can authorize access", "full replacement disguised as a sprint"],
    buyer_roles: { economic: "COO/GM", technical: "CTO/VP Engineering", product: "VP Product/CPO", router: "Head of Engineering" },
    trigger_types: ["enterprise launch", "platform migration", "major support hiring", "delayed roadmap commitment", "announced AI initiative creating production pressure"],
    problem_hypothesis: "A consequential product outcome is stuck between prototype and production and is blocking a launch, customer, or revenue commitment.",
    first_offer: "4–6 week Senior Engineering Delivery Sprint owning one consequential product slice end to end.",
    price: { model: "one_time", min: 40000, max: 60000, unit: "sprint" },
    proof_required: ["flagship delivery case", "delivery process + security/access model", "reviewable production result with tests and controls"],
    discovery_questions: ["Which product outcome is stuck and what is the consequence of delay?", "Who owns it and can grant system/data access?", "What acceptance criteria define done?"],
    success_metrics: ["reviewable production result deployed", "acceptance tests pass", "handoff accepted by internal team"],
    expansion_path: "Three-month Engineering Ownership Program → Managed Platform & AI Reliability.",
  },
  {
    play_id: "GNK-BE-01",
    brand: "gnk",
    strategy_version: STRATEGY_VERSION,
    name: "Backend Risk and Stabilization Sprint",
    target_account_definition: "Software/operations-heavy company with a high-risk backend, platform, integration, or reliability boundary under scale or change pressure.",
    hard_disqualifiers: ["no system access", "cheap staff-aug request", "broad platform rebuild without a bounded slice", "no measurable reliability/scale consequence"],
    buyer_roles: { economic: "CTO", technical: "VP Engineering / Platform Lead", product: null, router: "Engineering Manager" },
    trigger_types: ["public incident", "reliability/scale hiring", "platform migration", "major integration launch", "enterprise customer expansion"],
    problem_hypothesis: "One risky system boundary is expensive or unsafe to change and is absorbing senior time instead of shipping.",
    first_offer: "Backend Risk and Stabilization Sprint on one high-risk slice, with tests, observability, and rollback.",
    price: { model: "one_time", min: 35000, max: 50000, unit: "sprint" },
    proof_required: ["anonymized backend rescue case with reliability evidence", "delivery/security process page"],
    discovery_questions: ["Which boundary is risky to change or hard to test?", "What failure mode or scale pressure is driving this now?", "What does 'stabilized' mean measurably?"],
    success_metrics: ["stabilization slice delivered with tests/observability", "acceptance thresholds met", "risk reduced against a baseline where one exists"],
    expansion_path: "Modernization program or Managed Platform & AI Reliability retainer.",
  },
  {
    play_id: "GNK-DATA-01",
    brand: "gnk",
    strategy_version: STRATEGY_VERSION,
    name: "Data and Automation Delivery Sprint",
    target_account_definition: "Operations-heavy business with an expensive manual workflow spanning several systems (imports/exports, reconciliation, handoffs).",
    hard_disqualifiers: ["one-off creative task", "vague desire to 'use AI'", "no measurable operational cost", "no usable data/system access"],
    buyer_roles: { economic: "COO", technical: "Head of Engineering", product: null, router: "Director of Business Systems / RevOps" },
    trigger_types: ["operational scale-up", "business-systems hiring", "migration off spreadsheets/Airtable/Zapier", "reporting/data-quality pressure"],
    problem_hypothesis: "A business-critical workflow still moves through manual handoffs, creating delay, rework, and silent errors.",
    first_offer: "Workflow mapping + one automation slice for the highest-friction handoff.",
    price: { model: "one_time", min: 40000, max: 60000, unit: "sprint" },
    proof_required: ["before/after workflow map", "delivery process page", "reusable code + operating notes handoff"],
    discovery_questions: ["Which handoff is most expensive today?", "What are the real inputs/outputs and who owns them?", "What baseline cost/time exists to measure against?"],
    success_metrics: ["one manual handoff automated to production", "labor/error reduction vs baseline where one exists", "handoff accepted"],
    expansion_path: "Engineering Ownership Program across adjacent workflows.",
  },
  {
    play_id: "GNK-MOD-01",
    brand: "gnk",
    strategy_version: STRATEGY_VERSION,
    name: "Modernization or Technical Rescue Sprint",
    target_account_definition: "Company running a legacy system that still powers the business, or facing a troubled build / contractor rescue / incident follow-up.",
    hard_disqualifiers: ["cheap audit-only request", "broad rewrite with no bounded slice", "no owner", "no production consequence"],
    buyer_roles: { economic: "Founder/CEO/GM", technical: "CTO / Engineering lead", product: null, router: "Engineering Manager" },
    trigger_types: ["production incident", "stalled build", "contractor/vendor project needing rescue", "legacy modernization initiative", "new technical leader"],
    problem_hypothesis: "A core legacy path or troubled build is risky and expensive to change, and the team needs a clear read plus one controlled slice.",
    first_offer: "Assessment + one controlled modernization/stabilization slice on the highest-risk path.",
    price: { model: "one_time", min: 35000, max: 50000, unit: "sprint" },
    proof_required: ["rescue intake template", "anonymized rescue case", "delivery/security process page"],
    discovery_questions: ["Which path is central and most fragile?", "What triggered this now (incident, deadline, handover)?", "What does a safe first slice look like with rollback?"],
    success_metrics: ["highest-risk slice stabilized/modernized in production", "rollback-aware delivery", "next-step migration decision documented"],
    expansion_path: "Modernization program → managed reliability.",
  },
  {
    play_id: "GNK-AI-01",
    brand: "gnk",
    strategy_version: STRATEGY_VERSION,
    name: "Production AI Workflow Sprint",
    target_account_definition: "B2B/vertical SaaS or ops-heavy team with a valuable AI-assisted workflow that must move from experiment to controlled production.",
    hard_disqualifiers: ["prototype/demo only", "no real data or system access", "no human-review or control requirements considered", "vague 'add AI' with no workflow"],
    buyer_roles: { economic: "COO", technical: "CTO/VP Engineering", product: "VP Product", router: "Head of Engineering" },
    trigger_types: ["announced AI initiative", "agent project with unclear economics/controls", "AI/ML hiring", "compliance/review workflow pressure"],
    problem_hypothesis: "A valuable AI workflow is stuck because it isn't safely connected to real data/systems with validation, approval, audit, and failure handling.",
    first_offer: "Production AI Workflow Sprint: one workflow with integration, evals, controls, deployment, and handoff.",
    price: { model: "one_time", min: 40000, max: 60000, unit: "sprint" },
    proof_required: ["Production AI Control Checklist (data/tools/permissions/evals/approval/audit/failure/ownership)", "eval set + acceptance thresholds", "delivery process page"],
    discovery_questions: ["Which steps are deterministic vs AI-suited vs must-never-automate?", "What acceptance thresholds define good?", "Where must a human approve?"],
    success_metrics: ["one AI workflow in controlled production", "eval thresholds met", "controls/audit/fallback in place"],
    expansion_path: "Managed Platform & AI Reliability retainer; additional workflows/business units.",
  },
  {
    play_id: "OHUB-ISP-01",
    brand: "outagehub",
    strategy_version: STRATEGY_VERSION,
    name: "Power-context Operations Pilot (Telecom/ISP)",
    target_account_definition: "Regional telecom/ISP with a Canadian service-area footprint whose NOC, service-delivery, or customer-support ops interpret incidents and communicate with customers.",
    hard_disqualifiers: ["no Canadian operational exposure", "procurement-only route with no owner", "outage data is only a curiosity", "expects OutageHub to replace their own telemetry"],
    buyer_roles: { economic: "Head of Network Operations", technical: "Systems Architecture / Platform", operational: "NOC Manager / Service Delivery", router: "Customer Operations" },
    trigger_types: ["footprint expansion", "acquisition", "outage-readiness initiative", "support pressure", "network-operations hiring"],
    problem_hypothesis: "NOC/support cross-check external power status manually across a service area, slowing incident triage and customer comms.",
    first_offer: "One-region power-context operations pilot: one asset/customer set, API or webhook, one operational decision, 30-day evaluation.",
    price: { model: "recurring_plus_implementation", recurring: { min: 2000, max: 5000, unit: "month" }, implementation: { min: 5000, max: 25000, unit: "one_time" } },
    proof_required: ["coverage/freshness report for their footprint", "sample Canadian outage payloads", "notification routing examples", "honest coverage limitations"],
    discovery_questions: ["When would external power status change what a team says/prioritizes/checks next?", "Which region/service area to test first?", "Which fields are decision-grade?"],
    success_metrics: ["useful event coverage", "acceptable freshness", "fewer manual checks", "faster incident explanation or routing"],
    expansion_path: "Additional geography, sites, support systems, customer-status automation, embedded data.",
  },
  {
    play_id: "OHUB-FAC-01",
    brand: "outagehub",
    strategy_version: STRATEGY_VERSION,
    name: "Portfolio Monitoring Pilot (Multi-location Facilities)",
    target_account_definition: "Multi-location operator (property, long-term care, cold storage, greenhouses, industrial, logistics depots, field service) needing consistent portfolio monitoring and escalation.",
    hard_disqualifiers: ["single site only", "no Canadian exposure", "no owner for facilities/operations", "wants a one-off map lookup"],
    buyer_roles: { economic: "Regional Operations / Property Operations", technical: null, operational: "Facilities Director / Maintenance", router: "Emergency Preparedness" },
    trigger_types: ["portfolio growth", "facilities hiring", "emergency-readiness initiative", "weather event", "generator/maintenance focus"],
    problem_hypothesis: "Staff chase outage status manually across a portfolio, delaying tenant/resident comms and dispatch decisions.",
    first_offer: "30-day shadow-mode portfolio monitoring pilot for a defined set of sites: provider mapping, rules, escalation contacts.",
    price: { model: "recurring", recurring: { min: 500, max: 1500, unit: "month" }, implementation: { min: 5000, max: 25000, unit: "one_time" } },
    proof_required: ["locations matched with confidence", "false/stale alert control", "notification history", "tenant-comms workflow examples"],
    discovery_questions: ["Which portfolio/region to start with?", "Who must respond when a site is affected?", "What escalation and comms happen today?"],
    success_metrics: ["locations matched", "actionable events detected", "false/stale alerts controlled", "operator time saved"],
    expansion_path: "More sites, workflows, reporting, tenant/resident communications, integration.",
  },
  {
    play_id: "OHUB-EMBED-01",
    brand: "outagehub",
    strategy_version: STRATEGY_VERSION,
    name: "Embedded Outage-Intelligence Evaluation",
    target_account_definition: "Software/data platform (property/facilities software, support systems, emergency notification, IoT, insurance, network-ops) that can embed OutageHub and expose it to many downstream customers.",
    hard_disqualifiers: ["no Canadian downstream exposure", "no product/eng owner", "one-off map integration with no recurring path", "expects a custom fork below funding threshold"],
    buyer_roles: { economic: "VP Product", technical: "CTO/VP Engineering / Solutions Architect", product: "Head of Product", router: "Platform Lead" },
    trigger_types: ["Canada expansion", "product roadmap item depending on outage visibility", "integration/dashboard hiring", "customer commitments needing outage data"],
    problem_hypothesis: "The platform needs a reliable Canadian outage-data layer inside its product but building/maintaining the feed in-house is distracting and risky.",
    first_offer: "One-month embedded API evaluation + one integration slice for a single product workflow, with a technical proof note.",
    price: { model: "recurring", recurring: { min: 5000, max: 15000, unit: "month" } },
    proof_required: ["API docs + playground clarity", "sample payloads + error handling", "integration example", "coverage/latency/limits expectation-setting"],
    discovery_questions: ["Which product workflow would consume outage state first?", "What fields/SLAs do downstream customers need?", "Who owns the integration decision?"],
    success_metrics: ["integration slice proven in one workflow", "coverage/latency acceptable for the use case", "rollout recommendation accepted"],
    expansion_path: "Embedded rights across the customer base; commercial API + higher limits; enterprise intelligence.",
  },
];

export const PLAYS_BY_ID = Object.fromEntries(SALES_PLAYS.map((p) => [p.play_id, p]));
export const PLAYS_BY_BRAND = SALES_PLAYS.reduce((m, p) => ((m[p.brand] ||= []).push(p.play_id), m), {});
